### ISSUE TITLE
Selected values are not getting updated from outside of onChange event

### ISSUE THREAD

**Issue by arun567** [Aidurber/react-picky#78] opened 2018-10-16 20:43 UTC
## Version
2.05.

## Here's what went wrong:

<Picky
   value={this.state.selectedModel}
   onChange={this.handleModel}
   multiple={true}
>

=> Select one value in picky
=> Update the state from outside function and assign the empty value. i.e, selectedModel = [];
=> Select another value in picky
=> See, Instead of one value is selected its getting two values selected

**Comment by Aidurber** [comment] 2018-10-18 17:45
This is because Picky maintains an internal state, it's more trouble than it's worth. I'm going to work on a major release making Picky a controlled component only, I can't think of any value it provides being an uncontrolled component, and it causes bugs like this when props and state get out of sync.

**Comment by Aidurber** [comment] 2018-10-21 13:51
@karankumar89 @arun567 

I think I get what you mean. Though it might be an issue with your state, not Picky. If you're modifying the value externally, that state is the single source of truth for Picky. 

See: https://codesandbox.io/s/747z71zpxj

I check to see if the item exists before adding it. 

If I'm not quite on the same wavelength as you two, can you provide a simple CodeSandbox so I can investigate? 

Thanks :)

**Comment by karankumar89** [comment] 2018-10-22 18:34
@Aidurber Yea you're on the same track but mine was a different use case. I retried the steps and i think its been fixed in the **v4.0.1**.  The steps to reproduce is-

- Select All Elements
- Click on Add Button (only item3 and item4 are selected)
- Select options that are not selected (ex: item 5)
- v3.0.2 all elements get selected instead of just one (item 5)

### v4.0.1
https://codesandbox.io/s/j4j0j933lv
### v.3.0.2
https://codesandbox.io/s/w6yp3x159l

Thanks for looking into this :tada:

**Comment by Aidurber** [comment] 2018-10-22 20:01
@karankumar89 Ahhh I see! Thanks for the reproduction steps. 
I'll take a look tomorrow some time.

**Comment by Aidurber** [comment] 2019-01-09 16:55
@karankumar89 @arun567 Closing this. In the codesandboxes they were using React 16.0.0. The library depends on > 16.3.0

See https://github.com/Aidurber/react-picky/issues/92#issuecomment-452767921

Unable to replicate any of the above issues on the new 4.1.1 release with React > 16.3.0

**Closed by Aidurber** 2019-01-09 16:55 UTC
Labels: bug
