### ISSUE TITLE
Select all comes true by default on multi-select

### ISSUE THREAD

**Issue by rgercp** [Aidurber/react-picky#42] opened 2018-04-25 12:47 UTC
## Version
1.9.1
## Here's what went wrong:
Whatever multi-select I add the select all checkbox comes checked by default. I'm not sure if it is a bug or I'm doing something wrong. The example below illustrate the issue.

```javascript
import React from 'react'
import Picky from 'react-picky'

class Select extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      selected: null
    }
  }

  render () {
    return (
      <Picky
        multiple
        numberDisplayed={1}
        includeSelectAll
        includeFilter
        value={value}
        onChange={onChange}
        options={options}
        valueKey='value'
        labelKey='label'
        placeholder='Selecionar'
        selectAllText='Tudo'
        />
     )
  }
}
```

**Comment by Aidurber** [comment] 2018-04-25 13:07
Hi @rgercp,

I'm not able to replicate, could you please provide a CodeSandbox, you can use this as a base if it helps: https://codesandbox.io/s/oo8z2qy4my

Alternatively, if you could provide more details in your example: 
 - What `options` you are supplying?
 - What is your `onChange` 
 - What is your `value`.


It currently looks like it's an error in implementation, not a bug. If you're providing a `value` that means you intend on using it as a controlled compoment, so your value will be something from state, onChange will update that state.

**Comment by Aidurber** [comment] 2018-05-01 16:30
@rgercp Did you work out your issue, is it a bug or did you do something wrong?

**Comment by Aidurber** [comment] 2018-05-06 20:08
Closing - No reproduction.

**Closed by Aidurber** 2018-05-06 20:08 UTC
Labels: Needs repro/example
