### ISSUE TITLE
"Select All" filtered values

### ISSUE THREAD

**Issue by SimonChris** [Aidurber/react-picky#169] opened 2019-08-15 09:23 UTC
When typing into the searchbox, the Select All option disappears. I can override the Select All rendering, to make sure it is always shown, but then it still selects all the options, not just the ones matching the search text.

I would like to be able to select all the options actually shown in the dropdown when filtering and only them. Is there any way to accomplish this?

**Comment by Aidurber** [comment] 2019-08-15 10:54
Using a combination of `onFiltered` and `renderSelectAll` you can change what happens inside the custom render. 

See this rough example:
https://codesandbox.io/s/picky-only-select-all-filtered-xztnh

When the filter is changed, we store the filtered results in the component state. With the custom select all we check if we're filtered, if so then add the filtered results as the selected values. 

I didn't implement de-selecting, that'll need some work to go through the filtered results and remove them if they already exist etc. 

The example should get you most of the way.

**Comment by SimonChris** [comment] 2019-08-15 14:09
Thank you :). Are there any plans to add something like this as a standard option?

**Comment by Aidurber** [comment] 2019-08-15 14:28
Not currently, I personally don't use Picky in any of my projects so I don't have much reason to develop. I'll fix bugs, accept PRs, and add enhancements when I'm not busy. Though this seems like a good suggestion. I'll mark this as a good first issue, if no-one gets around to it then I might do eventually. 

Probably a prop like: 

`selectAllMode` with options like: `default`, `filtered` 
or just another boolean `selectAllOnlyFiltered` the name is nasty but at least it's accurate 😁

**Comment by SimonChris** [comment] 2019-08-15 14:29
Thanks for the quick reply :). If I get around to this, I may send you a PR.

**Comment by HarishTeens** [comment] 2019-10-03 16:33
I think I can implement the deselect option , what I'm thinking is static select all and deselect all buttons , will do their selections and deselections for all or just the filters. Would that be right?

**Comment by Aidurber** [comment] 2019-10-03 20:17
Hi @HarishTeens,
No I don't think that would be correct. The behaviour that Simon requested is that when the user has filtered the list and they press "Select All", that it only selects the filtered results. 

So let's say you have a list: 
- Moon
- Boo
- Cat

You then filter "oo", the list becomes: 
- Moon
- Boo

When you press "Select All", it will select both Moon and Boo, but not Cat. 

Currently it will still select all options. 

**Possible Solution**
An additional prop is added called `selectAllMode` which has 2 modes: `default` and `filtered`. 

`default` does as it currently does. 

`filtered` will only select the currently filtered options. 

Does that make sense?

Don't be afraid of asking more questions 😀

**Comment by HarishTeens** [comment] 2019-10-04 07:17
Yes I understood , when filtered , select all button will select only the filtered ones, i.e. Moon and Boo

**Comment by HarishTeens** [comment] 2019-10-04 09:02
And To be honest I don't know how to build or run packages , I've just used them in my projects, I was following the contributing.md file , it said to write a failing test on step 5 , i dont know testing too, would you help me out here?

**Comment by Aidurber** [comment] 2019-10-05 12:14
Hello @HarishTeens, 

Apologies for the late reply I was out to a party yesterday after work. 

Yes I can help you. 

I've updated the contributing.md with steps on how to do some manual testing locally. They may help you. 

So if you got up to step 4, we're almost done with the boring stuff. 

I understand that testing can be quite daunting but once you grasp it you won't look back. If you're serious about getting into testing I recommend [Kent C Dodds' Testing Javascript Course](https://testingjavascript.com/), it's quite expensive but I saw it as an investment in myself. 

After looking into this issue there are somethings that need to happen first. Recently there was a code change that hides the "select all" when the component is filtered. 

This is quite a tricky issue after thinking about it which requires quite a few code changes. 

Firstly, can you sync your fork with master. I've published some changes that will make it a little easier for you to contribute, you can read [Syncing a fork](https://help.github.com/en/articles/syncing-a-fork) on how to do that. Once that's done take another look at the contributing document, I've added an example directory which allows you to view your changes as you make them. 

Here is a failing test that I've written, you can paste it into `Picky.test.js` at line 509:

```javascript
it('should select only filtered when selectAllMode is "filtered"', () => {
      // We're going to be listening for changes so we're going to need a mock function.
      const mockOnChange = jest.fn();
      // Specify the options that picky is going to use
      const options = ['Boo', 'Moon', 'Cat', 'Dog'];

      // Mount Picky with Enzyme
      const wrapper = mount(
        <Picky
          options={options}
          value={['Dog']}
          onChange={mockOnChange}
          multiple={true}
          filterDebounce={0}
          open={true}
          selectAllMode="filtered"
          includeFilter={true}
          includeSelectAll={true}
        />
      );

      /**
       *  Lets change the filter input to 'oo', this should leave us with 2 options in the filter
       *  - Moon
       *  - Boo
       */
      wrapper
        .find(sel('picky__filter__input'))
        .simulate('change', { target: { value: 'oo' } });
      // Find the Select All button in the DOM
      const selectAllButton = wrapper.find(sel('selectall'));
      // Click the select all button
      selectAllButton.simulate('click');

      // The value should be "Moon" and "Boo"
      // Dog was selected before so it should still be returned
      expect(mockOnChange).toHaveBeenLastCalledWith(['Dog', 'Boo', 'Moon']);

      // Deselect all
      selectAllButton.simulate('click');
      // Should be the original values when we deslect, as we don't want to deselect everything
      expect(mockOnChange).toHaveBeenLastCalledWith(['Dog']);

      // Remove the filter text from 'oo' to ''
      wrapper
        .find(sel('picky__filter__input'))
        .simulate('change', { target: { value: '' } });

      // Lets select all again when we have no filter
      selectAllButton.simulate('click');

      // Should return all values since we're no longer filtered and we can see every option
      expect(mockOnChange).toHaveBeenLastCalledWith([
        'Boo',
        'Moon',
        'Cat',
        'Dog',
      ]);

      // Lets deselect all when we're not filtered. This should completely remove all options
      selectAllButton.simulate('click');
      expect(mockOnChange).toHaveBeenLastCalledWith([]);
    });
```

Hopefully that makes sense with the comments. Now you don't need to worry about writing the test. You can just focus on adding the feature. 

When you're developing, in your terminal run `yarn test --watch` once you've implemented the feature all tests should pass and we're good to go.

**Comment by Aidurber** [comment] 2019-10-05 12:16
It's worth noting that I've already added the `selectAllMode` prop to fix a bug that this feature would have caused. 
You can see it here: https://github.com/Aidurber/react-picky/pull/181

**Comment by HarishTeens** [comment] 2019-10-06 18:42
Wow thank you very for explaining everything, this is really a lot to process definitely  I will go through all of it and get back to you...

**Comment by Aidurber** [comment] 2019-10-06 18:50
You're right there is a lot to process, and as I mentioned above you picked a really tricky issue 😁 
Let me know if you have any issues, happy to help where I can.

**Comment by HarishTeens** [comment] 2019-10-10 16:36
I have done the part where it selects the filteredOptions only when select all button is clicked,
Now if the filter is cleared or changed what should Happen?
Should I simply deselect everything or select whatever filtered item remaining?

**Comment by Aidurber** [comment] 2019-10-10 16:57
So if we stick with the Moon, Boo, Cat example. 

If you search "oo" and select all, that has Moon and Boo selected. 
If you clear the filter, Moon and Boo should still be selected and the list should no longer be filtered, so you should see Cat in that list.

**Comment by HarishTeens** [comment] 2019-10-10 17:01
Okay cool that is what I have done , Test case has passed  , I'm giving PR in few minutes

**Comment by Aidurber** [comment] 2019-10-10 17:05
Nice work, I'll take a look shortly. I'll be cooking my dinner soon so it might be after that when I get to reviewing it.

**Comment by HarishTeens** [comment] 2019-10-10 17:31
going back to my previous question , if i clear the filter , moon and boo should still be selected , but happens to the select all button?

**Comment by HarishTeens** [comment] 2019-10-10 17:42
https://github.com/Aidurber/react-picky/pull/185

**Comment by HarishTeens** [comment] 2019-10-11 05:05
Okay then , feel free to create a issue so that I can try to do something . And thank you so much for you support .

**Comment by SimonChris** [comment] 2019-10-31 09:16
What's the status on this?

**Comment by Aidurber** [comment] 2019-11-03 17:07
@SimonChris This has been released, thanks to @HarishTeens 
I've also done the work to support indeterminate checkbox states. This is in version 5, breaking changes due to a port to TypeScript and minimum React version is now 16.8.0. 

Let me know if you have any issues, closing.

**Closed by Aidurber** 2019-11-03 17:07 UTC
Labels: enhancement

**Comment by SimonChris** [comment] 2019-11-03 17:48
"Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object."

I get this error whenever I try to render a Picky component with Picky 5.0. I've tried removing all the props with no effect.

**Comment by Aidurber** [comment] 2019-11-03 18:50
@SimonChris Thank you for testing this and my apologies for breaking the build 😭 I usually symlink into a local sandbox to test the distribution but it's been like a year since I had any issues. My bad! 

There seemed to be an issue with default exports and the build with CJS and ESM. I've changed Picky to a named export and updated the docs. Can you take a look at 5.0.1 when you have a chance and see if all of your issues are resolved. 

```
import { Picky } from "react-picky";
```

**Comment by SimonChris** [comment] 2019-11-04 08:26
I get the same error on 5.0.1.

**Comment by Aidurber** [comment] 2019-11-04 10:16
Hmmm, I can't reproduce it: 
https://codesandbox.io/s/simple-example-multi-and-single-select-zttud

**Comment by SimonChris** [comment] 2019-11-04 10:56
I had to change 'import Picky from "react-picky"' to
'import { Picky } from "react-picky";'

It works now :).

**Comment by Aidurber** [comment] 2019-11-04 11:14
Ahh 😂 I did say to do that. 

I've updated the docs to reflect that, glad I made this a breaking change 😁 

Thanks for all of your help @SimonChris!
